import {
  SiTypescript,
  SiJavascript,
  SiPython,
  SiGo,
  SiRust,
  SiOpenjdk,
  SiKotlin,
  SiCplusplus,
  SiReact,
  SiNodedotjs,
  SiDocker,
  SiPostgresql,
  SiTailwindcss,
  SiPrisma,
  SiRedis,
  SiMongodb,
  SiMysql,
  SiSqlite,
  SiNestjs,
  SiExpress,
  SiFastify,
  SiVite,
  SiGooglecloud,
  SiVercel,
  SiGithubactions,
  SiGraphql,
  SiRedux,
  SiReactquery,
  SiSass,
  SiGit,
  SiSentry,
  SiNginx,
  SiZod,
  SiStorybook,
  SiTrpc,
  SiRuby,
  SiRubyonrails,
  SiApachekafka,
  SiRabbitmq,
  SiGin,
} from "react-icons/si";
import {
  Mail,
  Github,
  Linkedin,
  Twitter,
  Facebook,
  Instagram,
  Youtube,
  Layout,
  Terminal,
  Cpu,
  Database,
} from "lucide-react";
import type { SocialMatcher, TechMatcher } from "./types";

export const ICON_MATCHERS: SocialMatcher[] = [
  { keywords: ["mail", "mailto:"], Icon: Mail },
  { keywords: ["github"], Icon: Github },
  { keywords: ["linkedin"], Icon: Linkedin },
  { keywords: ["twitter", "x.com"], Icon: Twitter },
  { keywords: ["facebook"], Icon: Facebook },
  { keywords: ["instagram"], Icon: Instagram },
  { keywords: ["youtube"], Icon: Youtube },
];

export const TECH_ICON_MATCHERS: TechMatcher[] = [
  { keywords: ["typescript", "ts"], Icon: SiTypescript },
  { keywords: ["javascript", "js"], Icon: SiJavascript },
  { keywords: ["python", "py"], Icon: SiPython },
  { keywords: ["java", "jvm"], Icon: SiOpenjdk },
  { keywords: ["go", "golang"], Icon: SiGo },
  { keywords: ["rust"], Icon: SiRust },
  { keywords: ["kotlin"], Icon: SiKotlin },
  { keywords: ["c++", "cpp"], Icon: SiCplusplus },
  { keywords: ["ruby"], Icon: SiRuby },

  { keywords: ["react", "next.js"], Icon: SiReact },
  { keywords: ["vite"], Icon: SiVite },
  { keywords: ["tailwind"], Icon: SiTailwindcss },
  { keywords: ["sass", "scss"], Icon: SiSass },
  { keywords: ["query", "tanstack"], Icon: SiReactquery },
  { keywords: ["redux"], Icon: SiRedux },
  { keywords: ["storybook"], Icon: SiStorybook },

  { keywords: ["node", "backend"], Icon: SiNodedotjs },
  { keywords: ["nestjs", "nest"], Icon: SiNestjs },
  { keywords: ["express"], Icon: SiExpress },
  { keywords: ["fastify"], Icon: SiFastify },
  { keywords: ["trpc"], Icon: SiTrpc },
  { keywords: ["graphql", "apollo"], Icon: SiGraphql },
  { keywords: ["zod"], Icon: SiZod },
  { keywords: ["rails", "rubyonrails"], Icon: SiRubyonrails },
  { keywords: ["gin"], Icon: SiGin },

  { keywords: ["postgres", "postgresql"], Icon: SiPostgresql },
  { keywords: ["redis"], Icon: SiRedis },
  { keywords: ["mongodb", "mongo"], Icon: SiMongodb },
  { keywords: ["mysql", "mariadb"], Icon: SiMysql },
  { keywords: ["sqlite"], Icon: SiSqlite },
  { keywords: ["prisma"], Icon: SiPrisma },
  { keywords: ["rabbitmq"], Icon: SiRabbitmq },
  { keywords: ["kafka", "apachekafka"], Icon: SiApachekafka },

  { keywords: ["docker", "container"], Icon: SiDocker },
  { keywords: ["gcp", "google cloud"], Icon: SiGooglecloud },
  { keywords: ["vercel"], Icon: SiVercel },
  { keywords: ["github actions", "ci/cd"], Icon: SiGithubactions },
  { keywords: ["git"], Icon: SiGit },
  { keywords: ["sentry"], Icon: SiSentry },
  { keywords: ["nginx"], Icon: SiNginx },

  { keywords: ["bash", "terminal", "shell"], Icon: Terminal },
  { keywords: ["shared", "core", "architecture"], Icon: Cpu },
  { keywords: ["web", "html", "css"], Icon: Layout },
  { keywords: ["database", "db"], Icon: Database },
];
