version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: portfolio_db
    ports:
      - "51214:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portfolio-network

  redis:
    image: redis:alpine
    container_name: portfolio_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - portfolio-network

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
    container_name: portfolio_app
    env_file:
      - ../.env
    ports:
      - "8800:8800"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres?schema=public
      - REDIS_URL=redis://redis:6379
      - PORT=8800
    depends_on:
      - postgres
      - redis
    networks:
      - portfolio-network

  client:
    build:
      context: ..
      dockerfile: docker/Dockerfile.client
    container_name: portfolio_client
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - portfolio-network

volumes:
  postgres_data:
  redis_data:

networks:
  portfolio-network:
    driver: bridge
