services:
  postgres:
    image: postgres:15-alpine
    container_name: portfolio_db
    ports:
      - "${DB_EXTERNAL_PORT:-51214}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portfolio-network

  redis:
    image: redis:alpine
    container_name: portfolio_redis
    volumes:
      - redis_data:/data
    networks:
      - portfolio-network

  app:
    image: ghcr.io/robertmon-dev/portfolio-app:latest
    container_name: portfolio_app
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?schema=public
      - REDIS_URL=redis://redis:6379
      - PORT=8800
    depends_on:
      - postgres
      - redis
    networks:
      - portfolio-network

  client:
    image: ghcr.io/robertmon-dev/portfolio-client:latest
    container_name: portfolio_client
    restart: always
    networks:
      - portfolio-network

  nginx:
    image: nginx:alpine
    container_name: portfolio_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
      - client
    networks:
      - portfolio-network

volumes:
  postgres_data:
  redis_data:

networks:
  portfolio-network:
    driver: bridge
