name: Quality Gate

on:
  workflow_call:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  check-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"

      - name: Install dependencies
        run: make install

      - name: Generate Prisma Client
        run: make db-generate

      - name: Build packages
        run: make build

      - name: Lint
        run: make lint

      - name: Run Tests
        run: make test
